name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          version:  15.x
      - name: Setup Python 3
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Clean install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
